### ISSUE TITLE
Emitter memory area declarations duplicated

### ISSUE THREAD

**Issue by leepike** [GaloisInc/tower#11] opened 2015-05-18 17:04 UTC
In the Compat backend, memory area declarations associated with emitters are being
replicated. E.g., for https://github.com/GaloisInc/ivory-tower-stm32/blob/master/tower-freertos-stm32-tests/examples/Simple.hs, we have generated (modulo alpha-renaming) like the following:

```
static int64_t emitter_tick_chan_1_thread_period_1ms_message_0;

static uint32_t emitter_tick_chan_1_thread_period_1ms_message_count;

static int64_t emitter_tick_chan_1_thread_period_1ms_message_0;

static uint32_t emitter_tick_chan_1_thread_period_1ms_message_count;
```
I don't think the bug can result in incorrect code, just noisy code.

**Comment by pchickey** [comment] 2015-05-18 17:25
It is probably a good time to update the freertos-stm32 package to use the new style backend and get rid of the compat backend completely.

**Comment by jameysharp** [comment] 2015-06-15 23:38
This isn't a Tower bug, and it's non-trivial to clean up correctly.

`ivory-backend-c` always generates both a declaration and a definition for every symbol. For public-visibility symbols, the declaration goes in the header file and the definition goes in the source file. For private-visibility symbols (which are generated with the `static` qualifier), both go in the source file.

For procedure symbols, even private-visibility definitions may need the declaration up-front. If a group of static functions is mutually recursive (which we discourage but don't prevent), then at least one function definitely needs a forward declaration. Otherwise, to remove the unnecessary forward declaration, we'd need to topo-sort the function calls in order to ensure that every function is defined before it's called.

I'm not sure whether memory area symbols can have mutually recursive definitions in their initializers. Hand-written C code can initialize two objects to each contain the address of the other, and I think Ivory can do the same given a struct containing a `Ptr Global`. Assuming that's legit, then the same issues apply to them as to procedures.

It would be nice to make `ivory-backend-c` do the right topo-sort and detect/break cycles at the same time, but barring that, I'm closing this as not a bug.

**Closed by jameysharp** 2015-06-15 23:38 UTC
